version: "3"
services:
  spark:
    build:
         context: ./docker
         dockerfile: Dockerfile
    ports:
      - "4000:80"
    networks:
      - webnet
    volumes: 
      - "./cityBikeResults:/result"
networks:
  webnet:

