version: "3"
services:
  spark1:
    build:
         context: ./docker
         dockerfile: Dockerfile
    ports:
      - "4000:80"
    networks:
      - webnet
        #    volumes: 
        #      - type: bind
        # source: ./
        # target: /result
networks:
  webnet:

